// Copyright 2026 The MathWorks, Inc.
// @vitest-environment happy-dom
//
// The N-D grid path, end to end, on a real MAT-file.
//
// Until this fixture existed the `(:,:,k)` page selector was covered only by
// hand-built payloads, so nothing checked that a rank-3 variable coming out of an
// actual parsed .mat lands in the grid correctly. That gap matters more here than
// elsewhere: MATLAB stores numeric arrays COLUMN-major, the payload is built from
// element labels rather than from byte order, and a positional read produces a
// grid that is wrong but entirely plausible.
//
// test/fixtures/nd_numeric.mat is generated by test/fixtures/make-fixtures.mjs and
// holds four variables chosen so this file can assert both sides of the gate:
//   Mat  2x3      plain 2-D
//   Nd   2x3x2    rank 3, non-square, so a row/column swap cannot hide
//   Nd4  2x2x2x2  rank 4, so the pager has two trailing subscripts
//   Vec  1x4      a vector, which must get NO payload at all
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { getModelFromBytes, invalidate } from '../src/host/SlddModel.js';
import { matrixPayload } from '../src/host/matrixPayload.js';
import { DexMatrixGrid } from '../src/webview/components/dex-matrix-grid.js';

// import.meta.dirname, not a URL relative to import.meta.url: under happy-dom
// that resolves against a document base rather than the file, and every read
// fails as `/test/fixtures/...`.
function bytes(name: string): ArrayBuffer {
  const b = readFileSync(join(import.meta.dirname, 'fixtures', name));
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
}

let seq = 0;
function variables(): Record<string, any> {
  const uri = `nd://fixture${seq++}.mat`;
  invalidate(uri);
  const root = getModelFromBytes(uri, 'nd_numeric.mat', bytes('nd_numeric.mat'));
  return Object.fromEntries((root.children ?? []).map((c: any) => [c.name, c]));
}

async function grid(matrix: any): Promise<DexMatrixGrid> {
  const el = new DexMatrixGrid();
  document.body.appendChild(el);
  el.matrix = matrix;
  await el.updateComplete;
  return el;
}

// What the user sees: one row per grid row, cells left to right.
function page(el: DexMatrixGrid, index: number): string[] {
  const rows: string[] = [];
  for (let r = 0; r < el.matrix!.dims[0]; r++) {
    const cells: string[] = [];
    for (let c = 0; c < el.matrix!.dims[1]; c++) {
      cells.push(el.cellText(r, c, index));
    }
    rows.push(cells.join(' '));
  }
  return rows;
}

describe('a real .mat parses into the payloads the grid expects', () => {
  it('holds all four variables, with the dims MATLAB reports', () => {
    const v = variables();
    expect(Object.keys(v)).toEqual(['Mat', 'Nd', 'Nd4', 'Vec']);
    expect(v.Nd.dims).toEqual([2, 3, 2]);
    expect(v.Nd4.dims).toEqual([2, 2, 2, 2]);
  });

  it('gives the rank-3 variable a payload in display order, not storage order', () => {
    // The bytes in the file are column-major: 1,4,2,5,3,6 for the first page. A
    // payload that echoed storage order would read 1,4,2,... here.
    const payload = matrixPayload(variables().Nd)!;
    expect(payload.name).toBe('Nd');
    expect(payload.dims).toEqual([2, 3, 2]);
    expect(payload.cells).toEqual(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']);
  });

  it('refuses the vector, so the gate is exercised by the same file', () => {
    expect(matrixPayload(variables().Vec)).toBeNull();
    // ...while the plain 2-D matrix in that same file passes it.
    expect(matrixPayload(variables().Mat)!.cells).toEqual(['1', '2', '3', '4', '5', '6']);
  });

  it('still shows the rank-3 variable as a descriptor in the tree', () => {
    // The glyph is the way in; the row itself does not try to print 12 numbers.
    expect(variables().Nd.displayValue).toBe('<2x3x2 double>');
  });
});

describe('the grid pages that fixture the way MATLAB would', () => {
  it('renders each page of the rank-3 variable as its own 2x3 slice', async () => {
    const el = await grid(matrixPayload(variables().Nd)!);
    expect(el.pageCount).toBe(2);
    expect(page(el, 0)).toEqual(['1 2 3', '4 5 6']);
    expect(page(el, 1)).toEqual(['7 8 9', '10 11 12']);
    el.remove();
  });

  it('labels those pages (:,:,1) and (:,:,2)', async () => {
    const el = await grid(matrixPayload(variables().Nd)!);
    expect([el.pageLabel(0), el.pageLabel(1)]).toEqual(['(:,:,1)', '(:,:,2)']);
    el.remove();
  });

  it('steps dimension 3 fastest across the rank-4 variable', async () => {
    // Each page of Nd4 is filled with its own number, so the page ORDER is
    // readable straight off the cell values.
    const el = await grid(matrixPayload(variables().Nd4)!);
    expect(el.pageCount).toBe(4);
    expect([0, 1, 2, 3].map((p) => el.pageLabel(p))).toEqual([
      '(:,:,1,1)',
      '(:,:,2,1)',
      '(:,:,1,2)',
      '(:,:,2,2)',
    ]);
    expect([0, 1, 2, 3].map((p) => el.cellText(0, 0, p))).toEqual(['1', '2', '3', '4']);
    el.remove();
  });

  it('names a cell with its full subscript, page included', async () => {
    const el = await grid(matrixPayload(variables().Nd)!);
    el.page = 1;
    await el.updateComplete;
    const cell = el.shadowRoot!.querySelector('[role="gridcell"]')!;
    expect(cell.getAttribute('aria-label')).toBe('Nd(1,1,2)');
    expect(cell.textContent!.trim()).toBe('7');
    el.remove();
  });
});
